# Generated by Django 5.1 on 2024-09-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_booking_alter_technicians_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
